// This file is auto-generated by scripts/generate-env-config.js
// Do not edit this file directly

export const env = {
  NEXT_PUBLIC_API_URL: 'http://localhost:8000',
  NEXT_PUBLIC_WS_URL: 'ws://localhost:8000/ws',
} as const;

export type EnvConfig = typeof env;
